const talks = [
  {
    id: "talk1",
    title: "The Future of AI in Software Development",
    speakers: ["Dr. Evelyn Reed"],
    category: ["AI", "Software Engineering"],
    duration: 60,
    description: "Explore how artificial intelligence is reshaping the landscape of software development, from automated code generation to intelligent debugging.",
    startTime: "10:00 AM",
  },
  {
    id: "talk2",
    title: "Mastering Cloud-Native Architectures",
    speakers: ["Liam Chen", "Sophia Patel"],
    category: ["Cloud", "Architecture", "DevOps"],
    duration: 60,
    description: "A deep dive into designing and implementing robust, scalable, and resilient cloud-native applications using modern practices.",
    startTime: "11:10 AM",
  },
  {
    id: "talk3",
    title: "Frontend Performance Optimization Techniques",
    speakers: ["Noah Miller"],
    category: ["Frontend", "Web Development"],
    duration: 60,
    description: "Learn practical strategies and tools to drastically improve the loading speed and responsiveness of your web applications.",
    startTime: "12:20 PM",
  },
  {
    id: "lunch",
    title: "Lunch Break",
    speakers: [],
    category: ["Break"],
    duration: 60,
    description: "Enjoy a delicious lunch and network with fellow attendees.",
    startTime: "01:20 PM",
  },
  {
    id: "talk4",
    title: "Demystifying Blockchain for Developers",
    speakers: ["Olivia Garcia"],
    category: ["Blockchain", "Security"],
    duration: 60,
    description: "Understand the core concepts of blockchain technology and its potential applications beyond cryptocurrencies.",
    startTime: "02:20 PM",
  },
  {
    id: "talk5",
    title: "Effective Data Visualization with D3.js",
    speakers: ["Ethan Kim", "Isabella White"],
    category: ["Data Science", "Frontend"],
    duration: 60,
    description: "Build interactive and compelling data visualizations using the powerful D3.js library.",
    startTime: "03:30 PM",
  },
  {
    id: "talk6",
    title: "DevOps Best Practices for Continuous Delivery",
    speakers: ["Ava Brown"],
    category: ["DevOps", "Automation"],
    duration: 60,
    description: "Implement industry-leading DevOps practices to achieve seamless and automated software delivery pipelines.",
    startTime: "04:40 PM",
  },
];

module.exports = talks;